=== ginoconexion/GSI-2015-2016/JEE/GIPSI-DWJ-pgirault-aballet/ResultatPronostique/src/main/resources/fr/emac/gipsi/gsi/truptil/calendrier.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://fr.emac.gipsi/gsi/calendrier" targetNamespace="http://fr.emac.gipsi/gsi/calendrier"
	elementFormDefault="qualified">

	<xsd:element name="match">
		<xsd:complexType>
			<xsd:attribute name="id" type="xsd:string" />
			<xsd:attribute name="date" type="xsd:date" />
			<xsd:attribute name="equipe1" type="xsd:string" />
			<xsd:attribute name="equipe2" type="xsd:string" />
			<xsd:attribute name="score1" type="xsd:int" />
			<xsd:attribute name="score2" type="xsd:int" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="groupe">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="match" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="competition">
	  <xsd:complexType>
	  	<xsd:sequence>
	  		<xsd:element ref="groupe" minOccurs="1" maxOccurs="unbounded" />
	  	</xsd:sequence>
	  	<xsd:attribute name="id" type="xsd:string" />
	  </xsd:complexType>
	</xsd:element>
	
</xsd:schema>

=== ginoconexion/GSI-2015-2016/JEE/GIPSI-DWJ-pgirault-aballet/ResultatPronostique/src/main/resources/fr/emac/gipsi/gsi/truptil/euro16Cal.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:competition xmlns:p="http://fr.emac.gipsi/gsi/calendrier" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://fr.emac.gipsi/gsi/calendrier calendrier.xsd ">
  <p:groupe id="A">
    <p:match date="" equipe1="" />
  </p:groupe>
  <p:groupe id="B">
    <p:match/>
  </p:groupe>
  <p:groupe id="C">
    <p:match/>
  </p:groupe>
  <p:groupe id="D">
    <p:match/>
  </p:groupe>
  <p:groupe id="E">
    <p:match/>
  </p:groupe>
  <p:groupe id="F">
    <p:match/>
  </p:groupe>
</p:competition>
